config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'pages#home'

  get '/about', to: 'pages#about'

  get '/contact', to: 'pages#contact'

  get '/terms', to: 'pages#terms'

   get '/privacy', to: 'pages#privacy'

   get '/enterprises', to: 'pages#enterprises'

   get '/ventures', to: 'pages#ventures'

   get '/team', to: 'pages#team'

   get '/careers', to: 'pages#careers'

   get '/apply_funding', to: 'beneficiaries#new'

   post '/get_funded', to: 'beneficiaries#create'

   get '/login', to: 'sessions#new'

   post '/login', to: 'sessions#create'

   delete '/logout', to: 'sessions#destroy'

   get '/beneficiary_login', to: 'beneficiary_sessions#new'

   post '/beneficiary_login', to: 'beneficiary_sessions#create'

   delete '/beneficiary_logout', to: 'beneficiary_sessions#destroy'

   get '/employee_login', to: 'employee_sessions#new'

   post '/employee_login', to: 'employee_sessions#create'

   delete '/employee_logout', to: 'employee_sessions#destroy'

   get '/open_account', to: 'investors#new'

   post '/open_account', to: 'investors#create'

   get '/check_out', to: 'payments#check'

   post '/process_payment', to: 'payments#check_out'

   get '/news', to: 'posts#index'

   get '/career', to: 'careers#show'

   post '/career_status', to:  'resumes#status'

   get '/status_login', to: 'status_sessions#new'

   post '/status_login', to: 'status_sessions#create'

   delete '/status_logout', to: 'status_sessions#destroy'

   get '/activate_investor', to: 'account_activations#edit_investor'

   get '/activate_beneficiary', to: 'account_activations#edit_beneficiary'

   patch '/avatar/:id', to: 'employees#update_avatar', as: 'avatar'

   put '/avatar/:id', to: 'employees#update_avatar'



   resources :beneficiaries do 
      resources :beneficiary_projects
   end
   
   resources :investors do
   	 resources :proposals
   	 resources :executors
   end

   resources :employees
   resources :clubs 
   resources :club_members
   resources :club_updates
   resources :posts
   resources :contacts
   resources :employee_calendar

   resources :careers do
      resources :resumes, only: [:index, :new, :create, :show]
   end

   resources :pages
   resources :stripe_logs, only: [:index, :new, :create]
   resources :system_logs, only: [:index, :create]
   resources :password_resets,     only: [:new, :create, :edit, :update]
   resources :news
   resources :nemabollon_files, only: [:index, :new, :create, :destroy]
end

app/models/employee.rb
class Employee < ApplicationRecord
	has_many :posts
	before_save { self.email = email.downcase }
	validates :firstname, presence: true
	validates :lastname, presence: true
	validates :role, presence: true
	validates :job_category, presence: true
	validates :job_location, presence: true
	validates :reports_to, presence: true
	validates :section, presence: true
	validates :contact_number, presence: true
	validates :employee_pid, presence: true
	validates :employee_rank, presence: true

	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  	validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
    has_secure_password
    validates :password, presence: true, length: { minimum: 6 }
    mount_uploader :avatar

    def Employee.digest(string)
    	cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
   	 	BCrypt::Password.create(string, cost: cost)
   	end

end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
  before_action :logged_in_employee,  only: [:edit, :update]  

	def index
    	@employees = Employee.all
  	end
  
  def new
  	@employee = Employee.new
  end

  def create
  	@employee = Employee.new(employee_params)
    @employee.email = "#{@employee.lastname}#{@employee.firstname}77@nemabollon.com"
    @employee.password = "nemabollon77"
    @employee.avatar = "none"
    @employee.user_type = "employee"
  	if @employee.save
  		#saved and logged in employee
      #SystemLog.new( system_event: "Employee account created for #{@employee.lastname},  #{@employee.firstname},  #{@employee.email} by #{current_employee.lastname}, #{current_employee.firstname},  #{current_employee.email} .", event_time: Time.now, users_id: current_employee.id).save
      flash[:success] = "Successfully created employee account"
     # redirect_to current_employee
      redirect_to @employee

  	else
      flash[:error] = "Could not create employee account"
  		#redirect_to current_employee
       redirect_to root_url

  	end
  end

  def show
  	@employee = Employee.find(params[:id])
    @allEmployees = Employee.all
    @investor= Investor.all
    @clubs = Club.all
    @beneficiaries = Beneficiary.all
    @logs = SystemLog.all
    @proposals = Proposal.all
     @club_updates = ClubUpdate.all
     @memos = NemabollonFile.all
     @events = EmployeeCalendar.all
     @posts = Post.all
  end

  def edit
    @employee = Employee.find(params[:id])
  end

  def update
    @employee = Employee.find(params[:id])
    if @employee.update(employee_params)
      flash[:success] = "Successfully Updated your Account"
      SystemLog.new( system_event: "Employee account updated for #{@employee.lastname},  #{@employee.firstname},  #{@employee.email} by #{current_employee.lastname}, #{current_employee.firstname},  #{current_employee.email} .", event_time: Time.now, users_id: current_employee.id).save
      redirect_to @employee
    else
      flash[:error] = "Could not update your account"
      redirect_to @employee
    end
  end

  def update_avatar
    @avatar = Employee.find(params[:id])
    if @avatar.update_attribute(:avatar, params[:employee][:avatar])
        flash[:success] = "Successfully Updated your Account"
        SystemLog.new( system_event: "Employee account updated for #{current_employee.lastname}, #{current_employee.firstname},  #{current_employee.email} .", event_time: Time.now, users_id: current_employee.id).save
        redirect_to @avatar
    else 
       flash[:error] = "Could not update your account"
       redirect_to @avatar
    end
  end

  def destroy
    @employee = Employee.find(params[:id])
    SystemLog.new( system_event: "Employee account destroyed for #{@employee.lastname},  #{@employee.firstname},  #{@employee.email} by #{current_employee.lastname},  #{current_employee.firstname},  #{current_employee.email} .", event_time: Time.now, users_id: current_employee.id).save
    @employee.destroy

    redirect_to employees_path
  end

   private
	def employee_params
		params.require(:employee).permit(:firstname, :lastname, :role, :email,  :password, :password_confirmation, :is_admin, :job_category, :job_location, :reports_to, :department, :section, :contact_number, :employee_pid, :employee_rank, :avatar)
	end

  def employee_edit_params
      params.require(:employee).permit(:avatar)
  end

   def logged_in_employee
      unless employee_logged_in?
        flash[:danger] = "Please log in."
        redirect_to employee_account_url
      end
    end
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/views/employees/_add_employee.html.erb
<div class="outer-form" style="left: 39%;">
</div>
<div class="forms">
<h4  class="contact-header"> ADD NEW EMPLOYEE </h4>
<%= form_for(:employee, url: employees_path) do |f| %>
	<%= f.label :firstname %><br>
	<%= f.text_field :firstname %><br>

	<%= f.label :lastname%><br>
	<%= f.text_field :lastname %><br>

	<%= f.label :role %><br>
	<%= f.select :role, ['CEO', 'Social Media Curator' ,'Business Manager', 'Software Engineer', 'Fundraising Coordinator'] %><br>
	<%= f.label :EmployeeRank%><br>
	<%= f.select :employee_rank, ['I', 'II', 'III', 'IV', 'V', 'VI', 'VII'] %><br>

	<%= f.label :Job_Category%><br>
	<%= f.select :job_category, ['I', 'II', 'III', 'IV', 'V', 'VI', 'VII'] %><br>

	<%= f.label :Job_Location %><br>
	<%= f.text_field :job_location %><br>

	<%= f.label :Reports_To %><br>
	<%= f.select :reports_to, ['Board Of Directors', 'Chief Executive Officer'] %><br>

	<%= f.label :Department %><br>
	<%= f.select :department, ['Office of the Chief Executive Officer', 'Administration and Human Resources', 'Operations', 'Project Management', 'Software Management', 'Accounting and Financing', 'Marketing', 'Public Relations' , 'Information and Broadcasting'] %><br>

	<%= f.label :Section %><br>
	<%= f.select :section, ['N/A'] %><br>

	<%= f.label :contact_number %><br>
	<%= f.text_field :contact_number %><br>

	<%= f.label :employee_pid %><br>
	<%= f.select :employee_pid, ['1-001', '2-001', '3-001', '4-001', '5-001', '6-001', '7-001', '8-001' , '9-001'] %><br>


	<%= f.label :is_admin %><br>
	<%= f.check_box :is_admin %><br>


	<%= f.submit "Add Employee" %>

<% end %>
</div>

app/views/employees/_all_employees.html.erb
<h4  class="contact-header"> TEAM MEMBERS </h4>

<%  @allEmployees.each do |employee| %>
	<div class="flip-container">
		<div class="flipper">
		<div class="front">	
		<p> Name : <%= employee.firstname %> <%= employee.lastname %></p>
	<p>Role : <%= employee.role %> </p>
	<p>Email : <%= employee.email %></p>
</div>
<div class="back">
	<% if employee.is_admin %>
	<%= link_to "View Employee", employee_path(employee), :class => "app-links" %>
	<%= link_to "Edit", edit_employee_path(employee), :class => "app-links" %>
	<%= link_to 'Destroy', employee_path(employee),
              method: :delete,
              data: { confirm: 'Are you sure?' }, :class => "app-links" %>
    <% end %>
</div>
</div>
</div>

<% end %>

app/views/employees/_avatar.html.erb
<%= form_for(@employee, url: avatar_path) do |f| %>
	<%= f.file_field :avatar %> <br>
	<%= f.submit "Update Avatar"%>
<% end %>

app/views/employees/_edit_employee.html.erb
<div class="forms" id="edit_employee_acct">
<h4  class="contact-header"> UPDATE YOUR EMPLOYEE ACCOUNT </h4>
<%= form_for(@employee, url: employee_path) do |f| %>
	<%= f.label :firstname %><br>
	<%= f.text_field :firstname %><br>

	<%= f.label :lastname%><br>
	<%= f.text_field :lastname %><br>

	<%= f.label :role %><br>
	<%= f.select :role, ['CEO', 'Business Manager', 'Software Engineer', 'Fundraising Coordinator'] %><br>

	<%= f.label :password %><br>
	<%= f.password_field :password  %><br>

	<%= f.label :password_confirmation %><br>
	<%= f.password_field :password_confirmation %><br>

	<%= f.file_field :avatar %> <br>
	
<% if current_employee.is_admin? %>
	<%= f.label :is_admin %><br>
	<%= f.check_box :is_admin %><br> 
<% end %>

	<%= f.submit "Update Account"%>

<% end %>
</div>

app/views/employees/_master_acct.html.erb
<div class="forms">

<h4 class="contact-header"> ADD EMPLOYEE</h4>
<div id="employee-form">
<%= form_for(@employee, url: employee_path) do |f| %>
	<%= f.label :firstname %><br>
	<%= f.text_field :firstname %><br>

	<%= f.label :lastname%><br>
	<%= f.text_field :lastname %><br>

	<%= f.label :role %><br>
	<%= f.select :role, ['CEO', 'Social Media Curator' ,'Business Manager', 'Software Engineer', 'Fundraising Coordinator'] %><br>
	<%= f.label :EmployeeRank%><br>
	<%= f.select :employee_rank, ['I', 'II', 'III', 'IV', 'V', 'VI', 'VII'] %><br>

	<%= f.label :Job_Category%><br>
	<%= f.select :job_category, ['I', 'II', 'III', 'IV', 'V', 'VI', 'VII'] %><br>

	<%= f.label :Job_Location %><br>
	<%= f.text_field :job_location %><br>

	<%= f.label :Reports_To %><br>
	<%= f.select :reports_to, ['Board Of Directors', 'Chief Executive Officer'] %><br>

	<%= f.label :Department %><br>
	<%= f.select :department, ['Office of the Chief Executive Officer', 'Administration and Human Resources', 'Operations', 'Project Management', 'Software Management', 'Accounting and Financing', 'Marketing', 'Public Relations' , 'Information and Broadcasting'] %><br>

	<%= f.label :Section %><br>
	<%= f.select :section, ['N/A'] %><br>

	<%= f.label :contact_number %><br>
	<%= f.text_field :contact_number %><br>

	<%= f.label :employee_pid %><br>
	<%= f.select :employee_pid, ['1-001', '2-001', '3-001', '4-001', '5-001', '6-001', '7-001', '8-001' , '9-001'] %><br>

	<%= f.label :email %><br>
	<%= f.email_field :email %><br>

	<%= f.label :password %><br>
	<%= f.password_field :password %><br>

	<%= f.label :password_confirmation %><br>
	<%= f.password_field :password_confirmation %><br>


	<%= f.label :is_admin %><br>
	<%= f.check_box :is_admin %><br>


	<%= f.submit "Add Employee" %>

<% end %>
</div>

</div>

app/views/employees/_team.html.erb
<p> Show Team Members </p>

app/views/employees/edit.html.erb
<% provide(:title, "Add Employee") %>
<div class="content">
<div class="forms">
<h4 class="contact-header"> ADD EMPLOYEE</h4>
<div id="employee-form">
<%= form_for(@employee, url: employee_path) do |f| %>
	<%= f.label :firstname %><br>
	<%= f.text_field :firstname %><br>

	<%= f.label :lastname%><br>
	<%= f.text_field :lastname %><br>

	<%= f.label :role %><br>
	<%= f.select :role, ['CEO', 'Social Media Curator' ,'Business Manager', 'Software Engineer', 'Fundraising Coordinator'] %><br>
	<%= f.label :EmployeeRank%><br>
	<%= f.select :employee_rank, ['I', 'II', 'III', 'IV', 'V', 'VI', 'VII'] %><br>

	<%= f.label :Job_Category%><br>
	<%= f.select :job_category, ['I', 'II', 'III', 'IV', 'V', 'VI', 'VII'] %><br>

	<%= f.label :Job_Location %><br>
	<%= f.text_field :job_location %><br>

	<%= f.label :Reports_To %><br>
	<%= f.select :reports_to, ['Board Of Directors', 'Chief Executive Officer'] %><br>

	<%= f.label :Department %><br>
	<%= f.select :department, ['Office of the Chief Executive Officer', 'Administration and Human Resources', 'Operations', 'Project Management', 'Software Management', 'Accounting and Financing', 'Marketing', 'Public Relations' , 'Information and Broadcasting'] %><br>

	<%= f.label :Section %><br>
	<%= f.select :section, ['N/A'] %><br>

	<%= f.label :contact_number %><br>
	<%= f.text_field :contact_number %><br>

	<%= f.label :employee_pid %><br>
	<%= f.select :employee_pid, ['1-001', '2-001', '3-001', '4-001', '5-001', '6-001', '7-001', '8-001' , '9-001'] %><br>

	<%= f.label :email %><br>
	<%= f.email_field :email %><br>

	<%= f.label :password %><br>
	<%= f.password_field :password %><br>

	<%= f.label :password_confirmation %><br>
	<%= f.password_field :password_confirmation %><br>


	<%= f.label :is_admin %><br>
	<%= f.check_box :is_admin %><br>


	<%= f.submit "Update Employee" %>

<% end %>
</div>
</div>

</div>
</div>

app/views/employees/index.html.erb
<% provide(:title, "All Employees") %>
<div class="content">
<%= link_to "Return to #{current_employee.firstname}'s Dashboard", current_employee, :class => "app-links" %><br>
<h4 class="contact-header"> ALL TEAM MEMBERS </h4>
<div id="add-employee">
<%= link_to image_tag("proposal.png", alt: "addEmployee", width: 40, height:40, float: "right" ), new_employee_path %>
<p>Add Employee </p>
</div>
<% @employees.each do |employee| %>
	<div class="flip-container">
		<div class="flipper">
		<div class="front">	
		<%= image_tag("employeeAvatar.png", class: "honor" , width: "100", height: "100") %>
		<p>Name : <%= employee.firstname %>
		<%= employee.lastname %></p>
		<p> Role : <%= employee.role %></p>
		<p> Email : <%= employee.email %></p>
	</div>
		<div class="back">

	<p><%= employee.is_admin %></p>
	<%= link_to "View Employee", employee_path(employee), :class => "app-links" %>
	<%= link_to "Edit", edit_employee_path(employee),  :class => "app-links" %>
	<%= link_to 'Destroy', employee_path(employee),
              method: :delete,
              data: { confirm: 'Are you sure?' },  :class => "app-links" %>
    	</div>
	</div>
	</div>
<% end %>
</div>

app/views/employees/new.html.erb
<% provide(:title, "Add Employee") %>
<div class="content">
<div class="outer-form mobile-form" >
	<%= link_to "All Employees", employees_path, :class => "app-links", :id => "all-employee-path" %>
</div>
<div class="forms">

<h4 class="contact-header"> ADD EMPLOYEE</h4>
<div id="employee-form">
<%= form_for(:employee, url: employees_path) do |f| %>
	<%= f.label :firstname %><br>
	<%= f.text_field :firstname %><br>

	<%= f.label :lastname%><br>
	<%= f.text_field :lastname %><br>

	<%= f.label :role %><br>
	<%= f.select :role, ['CEO', 'Social Media Curator' ,'Business Manager', 'Software Engineer', 'Fundraising Coordinator'] %><br>
	<%= f.label :EmployeeRank%><br>
	<%= f.select :employee_rank, ['I', 'II', 'III', 'IV', 'V', 'VI', 'VII'] %><br>

	<%= f.label :Job_Category%><br>
	<%= f.select :job_category, ['I', 'II', 'III', 'IV', 'V', 'VI', 'VII'] %><br>

	<%= f.label :Job_Location %><br>
	<%= f.text_field :job_location %><br>

	<%= f.label :Reports_To %><br>
	<%= f.select :reports_to, ['Board Of Directors', 'Chief Executive Officer'] %><br>

	<%= f.label :Department %><br>
	<%= f.select :department, ['Office of the Chief Executive Officer', 'Administration and Human Resources', 'Operations', 'Project Management', 'Software Management', 'Accounting and Financing', 'Marketing', 'Public Relations' , 'Information and Broadcasting'] %><br>

	<%= f.label :Section %><br>
	<%= f.select :section, ['N/A'] %><br>

	<%= f.label :contact_number %><br>
	<%= f.text_field :contact_number %><br>

	<%= f.label :employee_pid %><br>
	<%= f.select :employee_pid, ['1-001', '2-001', '3-001', '4-001', '5-001', '6-001', '7-001', '8-001' , '9-001'] %><br>

	<%= f.label :email %><br>
	<%= f.email_field :email %><br>

	<%= f.label :password %><br>
	<%= f.password_field :password %><br>

	<%= f.label :password_confirmation %><br>
	<%= f.password_field :password_confirmation %><br>


	<%= f.label :is_admin %><br>
	<%= f.check_box :is_admin %><br>


	<%= f.submit "Add Employee" %>

<% end %>
</div>

</div>

</div>

app/views/employees/show.html.erb
<% provide(:title, @employee.firstname) %>
<div class="content">
<div class='emp-avatar'>
 <%= image_tag @employee.avatar.url if @employee.avatar? %>
 <%= link_to "", current_employee, :class => "current_employee_reroute" %>
 <p id="change-pic"> Change Picture </p>
</div>


<div id="employee-dash">

<% if @employee.is_admin %>
<div class="employee-dash-opt">

<p id="emp-updates" class="emp-opts"> Club Updates </p>
<p id="emp-cal" class="emp-opts"> Calendar </p>
<p id="emp-post" class="emp-opts"> Add Blog Post </p>
<p id="emp-add" class="emp-opts"> Add Employee </p>
<p id="emp-news" class="emp-opts"> Add Club Update </p>
<p id="emp-priviledges" class="emp-opts"> Priviledges </p>
<p id="emp-clubs" class="emp-opts"> All Clubs </p>
<p id="emp-users" class="emp-opts"> All Users </p>
<p id="emp-managers" class="emp-opts"> Country Managers </p>
<p id="emp-owners" class="emp-opts"> All Enterprises </p>
<p id="emp-site" class="emp-opts"> Nemabollon Site </p>
<p id="emp-allEmp" class="emp-opts"> All Employees </p>
<p id="emp-proposals" class="emp-opts"> All Proposals </p>
<p id="emp-contacts" class="emp-opts"> System Log </p>

<% else %> 
<p id="emp-updates" class="emp-opts"> Club Updates </p>
<p id="emp-cal" class="emp-opts"> Calendar </p>
<p id="emp-post" class="emp-opts"> Add Blog Post </p>
<p id="emp-priviledges"   class="emp-opts"> My Priviledges </p>
<p id="emp-clubs"  class="emp-opts"> All Clubs</p>
<p id="emp-users" class="emp-opts"> All Users </p>
<p id="emp-managers" class="emp-opts"> Country Managers </p>
<p id="emp-owners" class="emp-opts"> Beneficiaries </p>
<p id="emp-news" class="emp-opts"> Add Club Update </p>
<% end %>

<%= link_to "LogOut", employee_logout_path, :id => "emp-logout", method: :delete, :class=> "app-links" %>
</div>
</div>

<div id="employee-content">
	<div id="emp-intro">
		<p > Welcome, <%= @employee.firstname %></p>
			<% if current_employee.role == 'Social Media Curator' %>
			<p> You are the Social Media Curator. </p>
			<p> As Social Media Curator your responsibilities include managing all Nemabollon Social Media Accounts, updating accounts with engaging content.Building a user following through engaging content.</p>
			<p> Below are the Social Media Account Credentials for your use. Please do not share these with anyone outside the Social Media Department. </p>
			<p style="font-size:0.85em">Social Media</p>
			<p style="font-size:0.85em">  Facebook, YouTube, Instagram, Twitter Account Credentials </p>
			<p style="font-size:0.85em"> email/username: nemabollon@gmail.com </p>
			<p style="font-size:0.85em"> password: LakeOfBlessings77 </p>
			<p> You are now the curator of these accounts and determine what is posted to them. Have fun. </p>
			<% end %>
	</div>


<div id="show-cal" class="empl-opts">
	<button class="dash-bttn-help" id="help-calendar">?</button>
	<%= render 'employee_calendar/show_events' %>
</div>

<div id="show-blog" class="empl-opts">
	<button class="dash-bttn-help" id="help-blog">?</button>
		<button class="dash-bttn" id="blog-show">All Articles</button>
	<button class="dash-bttn" id="blog-create">Create An Article</button>
	<div id="show-all-posts">
		<%= render 'posts/show' %>
	</div>

	<div id="create-new-post">
		<%= render 'posts/new' %>
	</div>
</div>


<div id="add-employee" class="empl-opts">
	<button class="dash-bttn-help" id="help-add-employee">?</button>
	<%= render 'employees/add_employee' %>
</div>

<div id="show-investors" class="empl-opts">
	<button class="dash-bttn-help" id="help-show-investors">?</button>
	<%= render 'investors/all_investors' %>
</div>

<div id="show-updates" class="empl-opts">
	<button class="dash-bttn-help" id="help-updates">?</button>
	<%= render 'club_updates/club_update' %>
</div>

<div id="show-clubs" class="empl-opts">
	<button class="dash-bttn-help" id="help-show-clubs">?</button>
	<%= render 'clubs/employee_clubs' %>
</div>

<div id="show-highlights" class="empl-opts">
	<button class="dash-bttn-help" id="help-show-highlights">?</button>
	<%= render 'pages/highlight' %>
</div>

<div id="show-employees" class="empl-opts">
	<button class="dash-bttn-help" id="help-show-employees">?</button>
	<%= render 'employees/all_employees' %>
</div>

<div id="show-managers" class="empl-opts">
	<button class="dash-bttn-help" id="help-show-country-managers">?</button>
	<%= render 'clubs/country_manager' %>
</div>

<div id="show-owners" class="empl-opts">
	<button class="dash-bttn-help" id="help-all-beneficiaries">?</button>
	<%= render 'beneficiaries/all_benficiaries' %>
</div>

<div id="show-proposals" class="empl-opts">
	<button class="dash-bttn-help" id="help-show-proposals">?</button>
	<%= render 'proposals/app_proposals' %>
	<div class ="employee-update-proposal">
		<%= render 'proposals/apply_prospects' %>
	</div>
</div>

<div id="show-contacts" class="empl-opts">
	<button class="dash-bttn-help" id="help-system-logs">?</button>
	<%= render 'system_logs/system_logs' %>
</div>

<div id="show-priviledges" class="empl-opts">
	<button class="dash-bttn-help" id="help-priviledges">?</button>
	<% if current_employee.is_admin? %>
		<p class="employee-links" style="text-align:center;"> You have Administrative Priviledges on the system </p>
	<% else %>
		<p class="employee-links" style="text-align:center;"> Please contact an administrator for more priviledges</p>
	<% end %>
	<div  id="edit-empl" class="priv-opts">
		<%= render 'employees/edit_employee' %>
	</div>
	<div id="upload-empl" class="priv-opts">
		<%= render 'nemabollon_files/upload_memos' %>
	</div>

	<div  id="all-memos-empl" class="priv-opts">
		<%= render 'nemabollon_files/all_memos' %>
	</div>


	<button class="dash-bttn" id="edit-empl-acct">Edit Account </button>
	<button class="dash-bttn" id="upload-empl-files">Upload File </button>
	<button class="dash-bttn" id="show-all-files">All Files </button>
</div>

<div id="create-club-update" class="empl-opts">
	<button class="dash-bttn-help" id="help-club-update">?</button>
	<%= render 'club_updates/club_update_form' %>
</div>

</div>

</div>
</div>


<div class="help" id="h-calendar">
	<p> Welcome to the System Calendar.</p>
	<p> This is where all employees will list their tasks and objectives. It is also where all meetings will be shown. </p>
	<p> It is a valuable resource in keeping track of your own tasks and other tasks in the system. </p>
	<p> Every employee is expected to add their weekly tasks to the calendar and mark them as completed once they are complete. </p>
	<p> The Calendar also allows upper management to interact and track different orders of business on the system. </p>
	<h4> USING THE CALENDAR </h4>
	<p> Click any month to reveal the tasks and other options for that month </p>
	<p> Use the interface to add your own tasks and update your progress which will be reflected on the calendar </p>
</div>
<div class="help" id="h-add-employee">
	<p> Welcome to the Add Employee Interface </p>
	<p> This is the interface HR uses to add new Employee Accounts to the system. </p>

</div>

<div class="help" id="h-blog">
	<p> Welcome to the Blog Interface</p>
	<p> This is where the all Social Media Posts are added to the System. </p>

</div>
<div class="help" id="h-show-investors">
	<p> View all Investors </p>
	<p> This interface allows you to view all investors in the system. Some details are priviledged and only accessible to the Employees with appropriate credentials. </p>
	<p> If you are unable to find what you are searching for please contact a supervisor.</p>
</div>
<div class="help" id="h-updates">
	<p> View all Company Updates </p>
	<p> This interface allows you to view all company news and updates in the system. </p>
</div>
<div class="help" id="h-show-clubs">
	<p> View all Clubs </p>
	<p> This interface allows you to view all Clubs in the system.</p>
	<p> The Clubs are the core of the application. These are the investments made by the Investors into projects.</p>
	<p> The Clubs are made up of Projects that are owned by Beneficiaries. The Beneficiaries use their approved Project Applications to apply for Funding which they are credited from the Club. </p>
</div>
<div class="help" id="h-show-highlights">
	<p> View Application Highlights </p>
	<p> This interface allows you to add highlights which are posted to the home page. </p>
	<p> These highlights reflect the best news to share with the world. </p>
</div>
<div class="help" id="h-show-employees">
	<p> View All Employees </p>
	<p> This interface allows you to view all Employees in the system. </p>
</div>
<div class="help" id="h-country-managers">
		<p> View All Country Managers </p>
	<p> This interface allows you to view all Country Managers in the system. </p>
</div>

<div class="help" id="h-all-beneficiaries">
		<p> View All Beneficiaries </p>
	<p> This interface allows you to view all Beneficiaries in the system. </p>
</div>
<div class="help" id="h-show-proposals">
		<p> View All Proposals </p>
	<p> This interface allows you to view all Proposals in the system. </p>
</div>
<div class="help" id="h-system-logs">
		<p> View System Logs </p>
	<p> This interface allows you to view all the activity in the system. </p>
</div>
<div class="help" id="h-priviledges">
		<p> View My Priviledges</p>
	<p> This interface allows you to know what actions you may perform on the system. </p>
</div>

<div class="upload-avatar">
	<button class="avatar-bttn">X</button>
	<%= render 'avatar' %>

</div>