config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'pages#home'

  get '/about', to: 'pages#about'

  get '/contact', to: 'pages#contact'

  get '/terms', to: 'pages#terms'

   get '/privacy', to: 'pages#privacy'

   get '/enterprises', to: 'pages#enterprises'

   get '/ventures', to: 'pages#ventures'

   get '/team', to: 'pages#team'

   get '/careers', to: 'pages#careers'

   get '/apply_funding', to: 'beneficiaries#new'

   post '/get_funded', to: 'beneficiaries#create'

   get '/login', to: 'sessions#new'

   post '/login', to: 'sessions#create'

   delete '/logout', to: 'sessions#destroy'

   get '/beneficiary_login', to: 'beneficiary_sessions#new'

   post '/beneficiary_login', to: 'beneficiary_sessions#create'

   delete '/beneficiary_logout', to: 'beneficiary_sessions#destroy'

   get '/employee_login', to: 'employee_sessions#new'

   post '/employee_login', to: 'employee_sessions#create'

   delete '/employee_logout', to: 'employee_sessions#destroy'

   get '/open_account', to: 'investors#new'

   post '/open_account', to: 'investors#create'

   get '/check_out', to: 'payments#check'

   post '/process_payment', to: 'payments#check_out'

   get '/news', to: 'posts#index'

   get '/career', to: 'careers#show'

   post '/career_status', to:  'resumes#status'

   get '/status_login', to: 'status_sessions#new'

   post '/status_login', to: 'status_sessions#create'

   delete '/status_logout', to: 'status_sessions#destroy'

   get '/activate_investor', to: 'account_activations#edit_investor'

   get '/activate_beneficiary', to: 'account_activations#edit_beneficiary'

   patch '/avatar/:id', to: 'employees#update_avatar', as: 'avatar'

   put '/avatar/:id', to: 'employees#update_avatar'



   resources :beneficiaries do 
      resources :beneficiary_projects
   end
   
   resources :investors do
   	 resources :proposals
   	 resources :executors
   end

   resources :employees
   resources :clubs 
   resources :club_members
   resources :club_updates
   resources :posts
   resources :contacts
   resources :employee_calendar

   resources :careers do
      resources :resumes, only: [:index, :new, :create, :show]
   end

   resources :pages
   resources :stripe_logs, only: [:index, :new, :create]
   resources :system_logs, only: [:index, :create]
   resources :password_resets,     only: [:new, :create, :edit, :update]
   resources :news
   resources :nemabollon_files, only: [:index, :new, :create, :destroy]
end

app/views/shared/_error_messages.html.erb
<% if @investor.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@investor.errors.count, "error") %>.
    </div>
    <ul>
    <% @investor.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_pledge.html.erb
    <%= form_for(:club_member, url: club_members_path) do |f| %>
    <%= f.hidden_field :investor_id, :value => @investor.id %>
    <%= f.hidden_field :club_id, :value => club.id %>
    <%= f.submit "Join", :id => "join-club", :class => "joined-club" %>
    <% end %>
<div id="dropin-container"></div>
  <script>
    var button = document.querySelector('#join-club');

    braintree.dropin.create({
      authorization: '<%= @client_token%>',
      container: '#dropin-container'
    }, function (createErr, instance) {
      button.addEventListener('click', function () {
        instance.requestPaymentMethod(function (requestPaymentMethodErr, payload) {
          // Submit payload.nonce to your server
        });
      });
    });
  </script>