config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'pages#home'

  get '/about', to: 'pages#about'

  get '/contact', to: 'pages#contact'

  get '/terms', to: 'pages#terms'

   get '/privacy', to: 'pages#privacy'

   get '/enterprises', to: 'pages#enterprises'

   get '/ventures', to: 'pages#ventures'

   get '/team', to: 'pages#team'

   get '/careers', to: 'pages#careers'

   get '/apply_funding', to: 'beneficiaries#new'

   post '/get_funded', to: 'beneficiaries#create'

   get '/login', to: 'sessions#new'

   post '/login', to: 'sessions#create'

   delete '/logout', to: 'sessions#destroy'

   get '/beneficiary_login', to: 'beneficiary_sessions#new'

   post '/beneficiary_login', to: 'beneficiary_sessions#create'

   delete '/beneficiary_logout', to: 'beneficiary_sessions#destroy'

   get '/employee_login', to: 'employee_sessions#new'

   post '/employee_login', to: 'employee_sessions#create'

   delete '/employee_logout', to: 'employee_sessions#destroy'

   get '/open_account', to: 'investors#new'

   post '/open_account', to: 'investors#create'

   get '/check_out', to: 'payments#check'

   post '/process_payment', to: 'payments#check_out'

   get '/news', to: 'posts#index'

   get '/career', to: 'careers#show'

   post '/career_status', to:  'resumes#status'

   get '/status_login', to: 'status_sessions#new'

   post '/status_login', to: 'status_sessions#create'

   delete '/status_logout', to: 'status_sessions#destroy'

   get '/activate_investor', to: 'account_activations#edit_investor'

   get '/activate_beneficiary', to: 'account_activations#edit_beneficiary'

   patch '/avatar/:id', to: 'employees#update_avatar', as: 'avatar'

   put '/avatar/:id', to: 'employees#update_avatar'



   resources :beneficiaries do 
      resources :beneficiary_projects
   end
   
   resources :investors do
   	 resources :proposals
   	 resources :executors
   end

   resources :employees
   resources :clubs 
   resources :club_members
   resources :club_updates
   resources :posts
   resources :contacts
   resources :employee_calendar

   resources :careers do
      resources :resumes, only: [:index, :new, :create, :show]
   end

   resources :pages
   resources :stripe_logs, only: [:index, :new, :create]
   resources :system_logs, only: [:index, :create]
   resources :password_resets,     only: [:new, :create, :edit, :update]
   resources :news
   resources :nemabollon_files, only: [:index, :new, :create, :destroy]
end

app/models/nemabollon_file.rb
class NemabollonFile < ApplicationRecord
	mount_uploader :memo
	validates :content_creator, presence: true
end

app/controllers/nemabollon_files_controller.rb
class NemabollonFilesController < ApplicationController
	before_action :logged_in_employee
	def index
		@memos = NemabollonFile.all
	end

	def new
		@memo = NemabollonFile.new
	end

	def create
		@memo = NemabollonFile.new(memo_params)
		@memo.content_creator = current_employee.email
		if @memo.save
			flash[:success] = "Your file was successfully uploaded"
			SystemLog.new( system_event: "Memo #{@memo.memo_name} uploaded file to system by #{current_employee.lastname}, #{current_employee.email}.", event_time: Time.now, users_id: current_employee.id).save
			redirect_to current_employee
		else 
			flash[:error] = "Upload Unsuccessful. Please try again"
			redirect_to current_employee
		end
	end

	def destroy
		@memo = NemabollonFile.find(params[:id])
		SystemLog.new( system_event: "Memo #{@memo.memo_name} deleted from system by #{current_employee.lastname}, #{current_employee.email}.", event_time: Time.now, users_id: current_employee.id).save
		@memo.destroy
		flash[:success] = "Memo successfully deleted"
		redirect_to current_employee
	end

	private
		def memo_params
			params.require(:memo).permit(:memo_name, :memo)
		end

		   def logged_in_employee
      unless employee_logged_in?
        flash[:danger] = "Please log in."
        redirect_to employee_account_url
      end
    end


end

app/helpers/nemabollon_files_helper.rb
module NemabollonFilesHelper
end

app/views/nemabollon_files/_all_memos.html.erb
<div id="memo-table">
<h4 class="contact-header"> All Files in system </h4>
<table class ="table-memo">
   <thead>.
      <tr>
         <th class="employee-links">Content Creator</th>
         <th class="employee-links">Memo Name</th>
         <th class="employee-links">Download Link</th>
         <th> </th>
      </tr>
   </thead>
   
   <tbody>
      <% @memos.each do |memo| %>
         
         <tr>
            <td class="employee-links"><%= memo.content_creator %></td>
            <td class="employee-links"><%= memo.memo_name %></td>
            <td><%= link_to "Download Memo", memo.memo_url, :class => "app-links" %></td>
            <% if current_employee.is_admin? %>
            <td><%= button_to "Delete",   nemabollon_file_path(memo), method: :delete,  confirm: "Are you sure that you wish to delete?" %></td>


            <% end %>
         </tr>
         
      <% end %>
   </tbody>
   
</table>
</div>

app/views/nemabollon_files/_upload_memos.html.erb
<div class="forms" id="upload_memo">
<%= form_for(:memo, url: nemabollon_files_path, html: { multipart: true }) do |f| %>
	  <%= f.label :memo_name %><br>
      <%= f.text_field :memo_name %><br>
      <%= f.label :attachment %><br>
      <%= f.file_field :memo %><br>
      <%= f.submit "Save" %>
 <% end %>
</div>