config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'pages#home'

  get '/about', to: 'pages#about'

  get '/contact', to: 'pages#contact'

  get '/terms', to: 'pages#terms'

   get '/privacy', to: 'pages#privacy'

   get '/enterprises', to: 'pages#enterprises'

   get '/ventures', to: 'pages#ventures'

   get '/team', to: 'pages#team'

   get '/careers', to: 'pages#careers'

   get '/apply_funding', to: 'beneficiaries#new'

   post '/get_funded', to: 'beneficiaries#create'

   get '/login', to: 'sessions#new'

   post '/login', to: 'sessions#create'

   delete '/logout', to: 'sessions#destroy'

   get '/beneficiary_login', to: 'beneficiary_sessions#new'

   post '/beneficiary_login', to: 'beneficiary_sessions#create'

   delete '/beneficiary_logout', to: 'beneficiary_sessions#destroy'

   get '/employee_login', to: 'employee_sessions#new'

   post '/employee_login', to: 'employee_sessions#create'

   delete '/employee_logout', to: 'employee_sessions#destroy'

   get '/open_account', to: 'investors#new'

   post '/open_account', to: 'investors#create'

   get '/check_out', to: 'payments#check'

   post '/process_payment', to: 'payments#check_out'

   get '/news', to: 'posts#index'

   get '/career', to: 'careers#show'

   post '/career_status', to:  'resumes#status'

   get '/status_login', to: 'status_sessions#new'

   post '/status_login', to: 'status_sessions#create'

   delete '/status_logout', to: 'status_sessions#destroy'

   get '/activate_investor', to: 'account_activations#edit_investor'

   get '/activate_beneficiary', to: 'account_activations#edit_beneficiary'

   patch '/avatar/:id', to: 'employees#update_avatar', as: 'avatar'

   put '/avatar/:id', to: 'employees#update_avatar'



   resources :beneficiaries do 
      resources :beneficiary_projects
   end
   
   resources :investors do
   	 resources :proposals
   	 resources :executors
   end

   resources :employees
   resources :clubs 
   resources :club_members
   resources :club_updates
   resources :posts
   resources :contacts
   resources :employee_calendar

   resources :careers do
      resources :resumes, only: [:index, :new, :create, :show]
   end

   resources :pages
   resources :stripe_logs, only: [:index, :new, :create]
   resources :system_logs, only: [:index, :create]
   resources :password_resets,     only: [:new, :create, :edit, :update]
   resources :news
   resources :nemabollon_files, only: [:index, :new, :create, :destroy]
end

app/models/resume.rb
class Resume < ApplicationRecord
	belongs_to :career
	attr_accessor :reset_token
	before_create :assign_user_type
	mount_uploader :attachment, AttachmentUploader
	validates :firstname, presence: true
	validates :lastname, presence: true
	validates :bioSketch, presence: true
	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
 	validates :email,  presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
	has_secure_password 
	validates :password, presence: true, length: { minimum: 6 }

def Resume.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

   def Beneficiary.new_token
    SecureRandom.urlsafe_base64
  end

   def password_reset_expired?
    reset_sent_at < 2.hours.ago
  end


   def assign_user_type
      self.user_type = "resume"
  end

   def create_reset_digest
    self.reset_token = Resume.new_token
    update_attribute(:reset_digest,  Resume.digest(reset_token))
    update_attribute(:reset_sent_at, Time.zone.now)
  end

  def send_password_reset_email
   NemabollonMailer.password_reset(self).deliver_now
  end
end

app/controllers/resumes_controller.rb
class ResumesController < ApplicationController
  before_action :logged_in_employee, only: [:index]
  def index
  	@resumes = Resume.all
  end

  def new
  	@resume = Resume.new
  end

  def create
    @career = Career.find(params[:career_id])
    @resume  = @career.resumes.create(resume_params)
  	if @resume.save
  		status_log_in @resume
      SystemLog.new( system_event: "New resume for #{@resume.lastname} for #{@career.job_title}  added to system", event_time: Time.now, users_id: @resume.id ).save
  		flash[:success] = "Your application has been submitted. Please use the Application Status link to track your status."
  		redirect_to career_resume_path(user.career_id, user.id)
  	else
  		flash[:error] = "Something went wrong. Unable to submit your application. Please try again."
  		render 'new'
  	end
  end

  def show
  	@resume = Resume.find(params[:id])
  end

  def status
  	@status = Resume.find_by(email: params[:email])
  end

  private
     def resume_params
     	params.require(:resume).permit(:firstname, :lastname, :bioSketch, :attachment, :email, :password, :password_confirmation)
     end

     def status_params
     	params.require(:resume).permit(:email, :password)
     end

      def logged_in_employee
        unless employee_logged_in?
          flash[:danger] = "Please log in."
          redirect_to root_url
        end
      end
end

app/helpers/resumes_helper.rb
module ResumesHelper
end

app/views/resumes/_all_resumes.html.erb
<h4  class="contact-header" style="margin-top: 0;"> ALL RESUMES </h4>
<%  @resumes.each do |resume| %>

<div class="flip-container">
	<div class="flipper">
	<div class="front">	
	<%= image_tag("avatar-01.png", class: "resumeIcon" , width: "100", height: "100") %><br>

	<p> Name : <%= resume.firstname %> <%= resume.lastname %></p>
	<p> Email  :<%= resume.email %></p>

</div>
<div class="back">
	<p> BioSketch :<%= resume.bioSketch %></p>
	<p> Download :<%= resume.attachment_url %></p>
</div>
</div>
</div>


<% end %>

app/views/resumes/index.html.erb
<% provide(:title, "All Resumes")%>
<div class="content">
<h4  class="contact-header" style="margin-top: 0;"> ALL RESUMES </h4>
<%  @resumes.each do |resume| %>

<div class="flip-container">
	<div class="flipper">
	<div class="front">	
	<%= image_tag("avatar-01.png", class: "resumeIcon" , width: "100", height: "100") %><br>

	<p> Name : <%= resume.firstname %> <%= resume.lastname %></p>
	<p> Email  :<%= resume.email %></p>

</div>
<div class="back">
	<p> BioSketch :<%= resume.bioSketch %></p>
	<p> Download :<%= resume.attachment_url %></p>
</div>
</div>
</div>


<% end %>
</div>

app/views/resumes/new.html.erb
<%provide(:title, "Upload Resume")%>
<div class="content">
	<div class="forms" style="margin-top: 120px;">
    <h4  class="contact-header"> PLEASE SUBMIT YOUR RESUME </h4>
	<%= form_for(:resume, url: career_resumes_path) do |f| %>
      <%= f.label :firstname %><br>
      <%= f.text_field :firstname %><br>

      <%= f.label :lastname %><br>
      <%= f.text_field :lastname %><br>


      <%= f.label :bioSketch %><br>
      <%= f.text_area :bioSketch %><br>

      <%= f.label :email %><br>
      <%= f.email_field :email %><br>

      <%= f.label :password %><br>
      <%= f.password_field :password %><br>

      <%= f.label :password_confirmation, "Confirmation" %><br>
      <%= f.password_field :password_confirmation %><br>

      <%= f.file_field :attachment %><br>

      <%= f.submit "Submit Resume" %>
    <% end %>
</div>
</div>

app/views/resumes/show.html.erb
<%provide(:title, "Resume")%>
<div class="content">

<p> Name : <%= @resume.firstname %>
<%= @resume.lastname %></p>

<p> Email : <%= @resume.email %></p>

<p> BioSketch : <%= @resume.bioSketch %></p>

<%= link_to "LogOut", status_logout_path , :id => "status-logout", method: :delete, :class=> "app-links" %>
</div>

app/views/resumes/status.html.erb
<% provide(:title, "Application Status") %>
<div class="content">
	
</div>